---
title: "Big Data with R"
subtitle: "Survey Results"
date: "01/08/2019"
output:
  xaringan::moon_reader:
    css: rstudio.css
    nature:
      countIncrementalSlides: yes
      highlightLines: yes
      highlightStyle: github
      ratio: 16:9
params:
  conference: 2019
---

```{r, setup,  include=FALSE}
options(htmltools.dir.version = FALSE)
library(tidyverse)
library(forcats)
library(ggjoy)

thm <- theme_bw() + 
  theme(
    panel.background = element_rect(fill = "transparent", colour = NA), 
    plot.background = element_rect(fill = "transparent", colour = NA),
    legend.background = element_rect(fill = "transparent", colour = NA),
    legend.key = element_rect(fill = "transparent", colour = NA),
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    text = element_text(size = 30),
    axis.title = element_text(size = 20)
  )
theme_set(thm)

source("tidy.R")

```

class: rstudio-slide
# R proficiency

```{r, fig.height=9, fig.width=20, dev.args = list(bg = "transparent"), echo = FALSE, message=FALSE}

lv <- tidy_responses %>%
  filter(question == "Which one describes your proficiency in R?") %>%
  group_by(answer, score) %>%
  summarise() %>%
  arrange(score) %>%
  pull(answer)

tidy_responses %>%
  filter(
    conference == params$conference,
    question == "Which one describes your proficiency in R?"
    ) %>%
  group_by(conference, answer, score) %>%
  tally() %>%
  ungroup() %>%
  mutate(
    s = factor(answer, lv),
    ratio = round(n / sum(n), 2) * 100,
    lab = paste0(ratio, "%")
    ) %>%
  ggplot() +
  geom_col(aes(s, ratio, fill = s), alpha = 0.5) + 
  geom_text(aes(s, ratio, label = lab), size = 10, vjust = 1) +
  labs(
    x = "",
    y = ""
  ) +
  scale_x_discrete(
labels = c("Danger", "Helps", "No danger", "Package", "CRAN"))
```

---
class: rstudio-slide
# Average use per package

```{r, fig.height=8, fig.width=20, dev.args = list(bg = "transparent"), echo = FALSE, message=FALSE}

tidy_responses %>%
  filter(
    conference == params$conference,
    group1 == "For each of these R packages, which one describes you best? ",
    !is.na(answer)
    ) %>%
  group_by(conference, question) %>%
  summarise(avg_score = mean(score)) %>%
  ungroup() %>%
  arrange(avg_score) %>%
  mutate(
    package = factor(question, question),
    lab = paste0(round(avg_score,2))
    ) %>%
  ggplot() +
  geom_col(aes(package, avg_score, fill = package), alpha = 0.5) + 
  geom_text(aes(package, avg_score, label = lab), size = 10, hjust = 1) +
  labs(x = "", y = "") +
  expand_limits(y= 4) +
  coord_flip() +
  scale_y_continuous(
    breaks = c(0, 1, 2, 3, 4),
    labels = c("Never", "Occasionally", "Most Days", "Can't live w/o it", "Helps folks")
    )
```




---
class: rstudio-slide
# SQL and Spark

```{r, fig.height=9, fig.width=20, dev.args = list(bg = "transparent"), echo = FALSE, message=FALSE}
tidy_responses %>%
  filter(
    conference == params$conference,
    group1 == "Regarding SQL and Spark experience, which one describes you best? ",
    !is.na(answer)
    ) %>%
  group_by(conference, question) %>%
  summarise(avg_score = mean(score)) %>%
  ungroup() %>%
  arrange(avg_score) %>%
  mutate(
    package = factor(question, question),
    lab = paste0(round(avg_score,2))
    ) %>%
  ggplot() +
  geom_col(aes(package, avg_score, fill = package), alpha = 0.5) + 
  geom_text(aes(package, avg_score, label = lab), size = 10, hjust = 1) +
  labs(x = "", y = "") +
  expand_limits(y= 4) +
  coord_flip() +
   scale_y_continuous(
    breaks = c(0, 1, 2, 3, 4),
    labels = c("Whats this?", "Once or twice", "On ocassion", "Often", "Anytime")
    )

```

---
class: rstudio-slide
# Databases

```{r, fig.height=8, fig.width=20, dev.args = list(bg = "transparent"), echo = FALSE, message=FALSE}

dbs <- strsplit("Microsoft SQL Server, Oracle, Redshift, Hive / Impala, PostgreSQL, Other, None yet,", ",")[[1]]

map_df(
  dbs,
  ~ tidy_responses %>%
    mutate(db = .x) %>%
    filter(
      str_detect(answer, .x),
      conference == params$conference,
      group1 == "Which databases do you access at work today, or plan to access soon?") %>%
    ungroup()
  ) %>%
  group_by(db) %>%
  tally() %>%
  arrange(n) %>%
  mutate(
    rank = factor(db, db),
    ratio = round(n / sum(n), 2) * 100,
    lab = paste0(ratio, "%")
    ) %>%
  ggplot() +
  geom_col(aes(rank, ratio, fill = rank), alpha = 0.5) + 
  geom_text(aes(rank, ratio, label = lab), size = 10, hjust = 1) +
  labs(x = "", y = "") +
  coord_flip()  +
  theme(axis.text.x = element_blank())
```

---
class: rstudio-slide
# Data Lake status

```{r, fig.height=8, fig.width=20, dev.args = list(bg = "transparent"), echo = FALSE, message=FALSE}


tidy_responses %>%
  filter(
    group1 == "What is the status of your data lake?",
    conference == params$conference,
    score != -1
    ) %>%
  group_by(answer, score) %>%
  tally() %>%
  ungroup() %>%
  arrange(score) %>%
  mutate(dl = factor(answer, answer)) %>%
  mutate(
    ratio = round(n / sum(n), 2) * 100,
    lab = paste0(ratio, "%")
    ) %>%
  ggplot() +
  geom_col(aes(dl, ratio, fill = dl), alpha = 0.5) + 
  geom_text(aes(dl, ratio, label = lab), size = 10, vjust = 1) +
  labs(x = "", y = "") +
  scale_x_discrete(
        labels = rev(c( "Mature", "Getting there", "Fully Mature",
               "Early", "Silos", "Under construction",
               "Road map", "Not close"))
  ) +
  theme(axis.text.y = element_blank())



```

---
class: rstudio-slide
# Available cluster

```{r, fig.height=8, fig.width=20, dev.args = list(bg = "transparent"), echo = FALSE, message=FALSE}

tidy_responses %>%
  filter(
    conference == params$conference,
    group1 == "Which kinds of clusters do you have access to at work?",
    !is.na(answer)
  ) %>%
  group_by(answer) %>%
  tally() %>%
  ungroup() %>%
  mutate(
    ratio = round(n / sum(n), 2) * 100,
    lab = paste0(ratio, "%")
    ) %>%
  ggplot() +
  geom_col(aes(answer, ratio, fill = answer), alpha = 0.5) + 
  geom_text(aes(answer, ratio, label = lab), size = 10, vjust = 1) +
  labs(x = "", y = "") +
  theme(axis.text.y = element_blank())
```




